version: "3.2"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./bin:/app/bin
      - ./lib:/app/lib
      - ./test:/app/test
    environment:
      - NODE_ENV=development
    container_name: chrome-har-capturer