version: 2.1

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:10

allBranchesAndVTag: &allBranchesAndVTag
  branches:
    only:
      - /.*/
  tags:
    only: /^v.*/
    #e.i v1.0.11

versionTag: &versionTag
  tags:
    only: /^v.*/
    #e.i v1.0.11
jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run:
          name: Run tests
          command: npm test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/project
          paths: .
      - run:
          command: ls
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: ls
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  node_package_ci_cd:
    jobs:
      - test:
          filters: *allBranchesAndVTag
      - deploy:
          context: Prod_Context_Observepoint
          filters: *versionTag
          requires:
            - test